2020-03-27 11:44:38,464 ERROR: Exception on /index [GET] [in /home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/penciledge/Desktop/FlaskApp/app/routes.py", line 37, in index
    prev_url=prev_url)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/base.html", line 26, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 7, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2020-03-27 11:45:17,315 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 13:20:37,337 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 13:27:09,666 ERROR: Exception on /explore [GET] [in /home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/penciledge/Desktop/FlaskApp/app/routes.py", line 152, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/base.html", line 51, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 7, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 157, in template
    document is interpreted as a reference to the start of that document,
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-03-27 13:31:34,054 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 14:14:16,624 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 15:31:32,655 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:61]
